import { CarDefinition, MissionDefinition } from '../types/game';

export const INITIAL_CARS: CarDefinition[] = [
  {
    id: 'city_compact',
    name: 'Pulse Hatch',
    category: 'City Compact',
    price: 0,
    unlocked: true,
    baseStats: {
      topSpeed: 130, // km/h
      acceleration: 6.0,
      handling: 8.5,
      braking: 7.5,
      durability: 6.5,
    },
    color: '#3B82F6', // Vivid Blue
    paintType: 'gloss',
    hasUnderglow: false,
    underglowColor: '#60A5FA',
    modelStyle: 'compact',
    description: 'Nimble and highly maneuverable compact hatchback. Ideal for tight urban parking and quick turns.',
  },
  {
    id: 'street_racer',
    name: 'Apex GT',
    category: 'Street Racer',
    price: 2500,
    unlocked: false,
    baseStats: {
      topSpeed: 190,
      acceleration: 8.8,
      handling: 7.8,
      braking: 8.5,
      durability: 5.5,
    },
    color: '#EF4444', // Racing Red
    paintType: 'metallic',
    hasUnderglow: false,
    underglowColor: '#F87171',
    modelStyle: 'racer',
    description: 'High-revving turbocharged sports coupe. Built for straight-line speed, highway overtaking, and rapid sprints.',
  },
  {
    id: 'urban_suv',
    name: 'Titan TX',
    category: 'Urban SUV',
    price: 4500,
    unlocked: false,
    baseStats: {
      topSpeed: 155,
      acceleration: 6.8,
      handling: 6.2,
      braking: 8.0,
      durability: 9.5,
    },
    color: '#10B981', // Emerald Forest
    paintType: 'metallic',
    hasUnderglow: false,
    underglowColor: '#34D399',
    modelStyle: 'suv',
    description: 'Heavy reinforced chassis with high impact resistance and solid stability on rough turns.',
  },
  {
    id: 'electric_hyper',
    name: 'Volt Spectre',
    category: 'Electric Hypercar',
    price: 8000,
    unlocked: false,
    baseStats: {
      topSpeed: 230,
      acceleration: 9.8,
      handling: 9.0,
      braking: 9.5,
      durability: 7.0,
    },
    color: '#8B5CF6', // Cyber Violet
    paintType: 'metallic',
    hasUnderglow: true,
    underglowColor: '#A78BFA',
    modelStyle: 'hyper',
    description: 'Dual-motor electric hypercar delivering near-instantaneous torque and razor-sharp aerodynamic grip.',
  },
  {
    id: 'classic_cruiser',
    name: 'Vanguard 70',
    category: 'Classic Muscle',
    price: 6000,
    unlocked: false,
    baseStats: {
      topSpeed: 175,
      acceleration: 8.2,
      handling: 6.5,
      braking: 6.8,
      durability: 8.5,
    },
    color: '#F59E0B', // Amber Gold
    paintType: 'gloss',
    hasUnderglow: false,
    underglowColor: '#FBBF24',
    modelStyle: 'classic',
    description: 'V8 roar and classic American muscle heritage. Raw mechanical power with distinct deep exhaust tone.',
  }
];

export const GAME_MISSIONS: MissionDefinition[] = [
  {
    id: 1,
    title: 'Drive to Destination',
    category: 'Drive',
    description: 'Navigate safely through urban traffic and reach the Downtown Plaza waypoint.',
    objectiveText: 'Drive to the glowing waypoint marker (0/1)',
    timeLimit: 90,
    targetWaypointsCount: 1,
    targetMaxDamage: 40,
    rewardCoins: 250,
    rewardXp: 150,
    unlocked: true,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'low',
  },
  {
    id: 2,
    title: 'Parking Challenge',
    category: 'Parking',
    description: 'Maneuver into the designated parking bay between the painted lines and hold steady.',
    objectiveText: 'Park inside the designated slot (Accuracy > 70%)',
    timeLimit: 75,
    targetParkSlotId: 'slot_1',
    targetMaxDamage: 25,
    rewardCoins: 350,
    rewardXp: 200,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'low',
  },
  {
    id: 3,
    title: 'Follow Traffic Rules',
    category: 'Rules',
    description: 'Drive along the avenues, obeying traffic signals and avoiding collisions or sidewalk bumps.',
    objectiveText: 'Reach 2 checkpoints with 0 traffic violations',
    timeLimit: 110,
    targetWaypointsCount: 2,
    targetMaxDamage: 20,
    rewardCoins: 450,
    rewardXp: 250,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'medium',
  },
  {
    id: 4,
    title: 'Time Challenge',
    category: 'Speed',
    description: 'Rush across the city grid and hit all 3 rapid checkpoints before the timer runs out!',
    objectiveText: 'Clear 3 checkpoints before the clock hits 0:00',
    timeLimit: 50,
    targetWaypointsCount: 3,
    targetMaxDamage: 35,
    rewardCoins: 500,
    rewardXp: 300,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DUSK',
    trafficDensity: 'medium',
  },
  {
    id: 5,
    title: 'Avoid Collision',
    category: 'Drive',
    description: 'Drive through heavy rush-hour traffic grid without sustaining more than 10% vehicle damage.',
    objectiveText: 'Cross the busy commercial boulevard (< 10% damage)',
    timeLimit: 80,
    targetWaypointsCount: 2,
    targetMaxDamage: 10,
    rewardCoins: 600,
    rewardXp: 350,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'high',
  },
  {
    id: 6,
    title: 'Traffic Signal Challenge',
    category: 'Rules',
    description: 'Pass through 4 active traffic intersections. Stop cleanly on red and advance smoothly on green.',
    objectiveText: 'Pass through 4 intersections with zero signal violations',
    timeLimit: 120,
    targetWaypointsCount: 4,
    targetMaxDamage: 30,
    rewardCoins: 700,
    rewardXp: 400,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'medium',
  },
  {
    id: 7,
    title: 'Delivery Mission',
    category: 'Delivery',
    description: 'Transport delicate parcels to the commercial sector. Avoid high-impact crashes and erratic bumps.',
    objectiveText: 'Deliver cargo to warehouse point (Keep damage < 15%)',
    timeLimit: 95,
    targetWaypointsCount: 2,
    targetMaxDamage: 15,
    rewardCoins: 800,
    rewardXp: 450,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DUSK',
    trafficDensity: 'medium',
  },
  {
    id: 8,
    title: 'Highway Drive',
    category: 'Speed',
    description: 'Hit the open outer highway ring. Maintain a cruising speed above 70 km/h for the checkpoint run.',
    objectiveText: 'Complete the perimeter loop at high speed',
    timeLimit: 65,
    targetWaypointsCount: 3,
    targetMaxDamage: 25,
    rewardCoins: 900,
    rewardXp: 500,
    unlocked: false,
    stars: 0,
    timeOfDay: 'DAY',
    trafficDensity: 'medium',
  },
  {
    id: 9,
    title: 'Night Drive',
    category: 'Drive',
    description: 'Cruising through the glowing neon night city. Navigate illuminated streets and night traffic.',
    objectiveText: 'Drive safely through the nighttime downtown circuit',
    timeLimit: 100,
    targetWaypointsCount: 3,
    targetMaxDamage: 30,
    rewardCoins: 1000,
    rewardXp: 550,
    unlocked: false,
    stars: 0,
    timeOfDay: 'NIGHT',
    trafficDensity: 'medium',
  },
  {
    id: 10,
    title: 'Advanced Parking',
    category: 'Parking',
    description: 'Master tight reverse angle parking in a narrow slot between luxury vehicles.',
    objectiveText: 'Reverse park with > 85% precision',
    timeLimit: 70,
    targetParkSlotId: 'slot_reverse_pro',
    targetMaxDamage: 15,
    rewardCoins: 1200,
    rewardXp: 700,
    unlocked: false,
    stars: 0,
    timeOfDay: 'NIGHT',
    trafficDensity: 'low',
  }
];

export const DRIVER_LEVELS = [
  { level: 1, title: 'Beginner Driver', xpRequired: 0 },
  { level: 2, title: 'Learner', xpRequired: 300 },
  { level: 3, title: 'City Driver', xpRequired: 800 },
  { level: 4, title: 'Skilled Driver', xpRequired: 1500 },
  { level: 5, title: 'Pro Driver', xpRequired: 2500 },
  { level: 6, title: 'Street Veteran', xpRequired: 4000 },
  { level: 7, title: 'Speed Enthusiast', xpRequired: 6000 },
  { level: 8, title: 'Precision Ace', xpRequired: 8500 },
  { level: 9, title: 'Highway Legend', xpRequired: 12000 },
  { level: 10, title: 'Grand Master', xpRequired: 16500 },
];

export const UPGRADE_CONFIG = {
  engine: {
    name: 'Engine Tuning',
    desc: 'Increases top speed and high-end power output.',
    baseCost: 300,
    costMultiplier: 1.8,
    statIncrease: 0.8,
  },
  brakes: {
    name: 'Sport Brakes',
    desc: 'Reduces stopping distance and enhances ABS response.',
    baseCost: 250,
    costMultiplier: 1.7,
    statIncrease: 0.9,
  },
  handling: {
    name: 'Suspension & Tires',
    desc: 'Sharpens steering responsiveness and grip during high-speed cornering.',
    baseCost: 280,
    costMultiplier: 1.75,
    statIncrease: 0.85,
  },
  durability: {
    name: 'Reinforced Chassis',
    desc: 'Strengthens bodywork against collision damage.',
    baseCost: 260,
    costMultiplier: 1.7,
    statIncrease: 1.0,
  },
  turbo: {
    name: 'Turbocharger',
    desc: 'Boosts 0-100 km/h acceleration and throttle response.',
    baseCost: 400,
    costMultiplier: 1.9,
    statIncrease: 1.1,
  },
};

export const COLOR_PALETTES = [
  { name: 'Racing Red', hex: '#EF4444' },
  { name: 'Cyber Blue', hex: '#3B82F6' },
  { name: 'Emerald Forest', hex: '#10B981' },
  { name: 'Amber Gold', hex: '#F59E0B' },
  { name: 'Vibrant Purple', hex: '#8B5CF6' },
  { name: 'Matte Stealth Black', hex: '#18181B' },
  { name: 'Glacier Pearl White', hex: '#F8FAFC' },
  { name: 'Neon Lime', hex: '#84CC16' },
  { name: 'Sunset Orange', hex: '#F97316' },
  { name: 'Electric Cyan', hex: '#06B6D4' },
];

export const UNDERGLOW_COLORS = [
  { name: 'None', hex: 'none' },
  { name: 'Neon Blue', hex: '#3B82F6' },
  { name: 'Cyber Purple', hex: '#A855F7' },
  { name: 'Laser Green', hex: '#22C55E' },
  { name: 'Solar Amber', hex: '#F59E0B' },
  { name: 'Inferno Red', hex: '#EF4444' },
  { name: 'Ice Cyan', hex: '#06B6D4' },
];
